version: '3.7'
#to run: docker compose up --build
services:
  bluesky:
    image: tudelft/bluesky
    build: .
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto/config:/mosquitto/config:ro"