version: '3.7'
#to run: docker compose up --build
services:
  bluesky:
    image: tudelft/bluesky
    build: .
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
    ports:
      - "11000:11000/tcp"
      - "11001:11001/tcp"
      - "12000:12000/tcp"
      - "12001:12001/tcp"
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto/config:/mosquitto/config:ro"